import { useEffect, useState, type FormEvent, type ReactNode, type SyntheticEvent } from "react";
import { AlertTriangle, Boxes, Check, ChevronLeft, ChevronRight, Copy, Edit3, ImageOff, LogOut, PackagePlus, Plus, RefreshCw, Search, Settings2, Trash2, Wrench, X } from "lucide-react";
import type { Bootstrap, Complementary, Connector, Kit, Profile, User } from "./types";

const money = (cents: number) => new Intl.NumberFormat("tr-TR", { style: "currency", currency: "TRY", maximumFractionDigits: 2 }).format((Number(cents) || 0) / 100);
const apiFetch = (url: string, init: RequestInit = {}) => fetch(url, { ...init, credentials: "include", headers: { ...(init.body ? { "content-type": "application/json" } : {}), ...(init.headers || {}) } });
const json = (method: string, body: unknown) => ({ method, body: JSON.stringify(body) });
type View = "kits" | "editor" | "catalogs";
type EditorMode = "create" | "edit" | "view";

export default function App() {
  const [user, setUser] = useState<User | null>(null);
  const [data, setData] = useState<Bootstrap | null>(null);
  const [kits, setKits] = useState<Kit[]>([]);
  const [view, setView] = useState<View>("kits");
  const [editor, setEditor] = useState<{ mode: EditorMode; kit?: Kit }>({ mode: "create" });
  const [loading, setLoading] = useState(true);
  const [authError, setAuthError] = useState("");
  const [notice, setNotice] = useState("");

  async function loadAll() {
    const [bootstrapResponse, kitsResponse] = await Promise.all([apiFetch("/api/bootstrap"), apiFetch("/api/kits")]);
    if (bootstrapResponse.status === 401) { setUser(null); setData(null); return; }
    if (!bootstrapResponse.ok || !kitsResponse.ok) throw new Error("Kit Studio verileri yüklenemedi");
    const bootstrap = await bootstrapResponse.json() as Bootstrap;
    setData(bootstrap); setUser(bootstrap.user); setKits(await kitsResponse.json() as Kit[]);
  }
  useEffect(() => { void (async () => { try { const response = await apiFetch("/api/auth/me"); if (response.ok) { const body = await response.json() as { user: User }; setUser(body.user); if (!body.user.must_change_password) await loadAll(); } } catch { setAuthError("Panel kimlik doğrulama servisine ulaşılamadı"); } finally { setLoading(false); } })(); }, []);
  async function login(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setAuthError(""); const form = new FormData(event.currentTarget); const response = await apiFetch("/api/auth/login", json("POST", { username: form.get("username"), password: form.get("password") })); if (!response.ok) { setAuthError(response.status === 502 ? "Panel servisine ulaşılamadı" : "Kullanıcı adı veya parola hatalı"); return; } const body = await response.json() as { user: User }; setUser(body.user); if (!body.user.must_change_password) await loadAll(); }
  async function logout() { await apiFetch("/api/auth/logout", { method: "POST" }); setUser(null); setData(null); setKits([]); }
  function openEditor(mode: EditorMode, kit?: Kit) { setEditor({ mode, kit }); setView("editor"); setNotice(""); }
  if (loading) return <div className="loading"><span className="spinner"/>Oturum denetleniyor…</div>;
  if (!user) return <LoginScreen onSubmit={login} error={authError}/>;
  if (user.must_change_password) return <PasswordChange user={user} onChanged={(next) => { setUser(next); void loadAll(); }} onLogout={logout}/>;
  if (!data) return <div className="loading"><span className="spinner"/>Katalog hazırlanıyor…</div>;
  const canWrite = user.role !== "readonly";
  return <div className="app-shell">
    <header className="topbar"><div className="brand-mark"><Wrench size={18}/></div><div className="brand-copy"><strong>DSDST</strong><span>Kit Studio</span></div><nav><button className={view === "kits" ? "nav-active" : ""} onClick={() => setView("kits")}><Boxes size={16}/>Kitler</button>{canWrite && <button className={view === "editor" && editor.mode === "create" ? "nav-active" : ""} onClick={() => openEditor("create")}><Plus size={16}/>Yeni Kit</button>}<button className={view === "catalogs" ? "nav-active" : ""} onClick={() => setView("catalogs")}><Settings2 size={16}/>Katalog Durumu</button></nav><div className="user-chip"><strong>{user.username}</strong><span>{user.role}</span></div><button className="icon-button" onClick={logout} aria-label="Çıkış yap"><LogOut size={18}/></button></header>
    {notice && <div className="global-notice">{notice}</div>}
    {view === "kits" && <KitList kits={kits} canWrite={canWrite} onOpen={openEditor} onChanged={loadAll} setNotice={setNotice}/>}
    {view === "editor" && <KitEditor key={`${editor.mode}-${editor.kit?.id || "new"}`} mode={editor.mode} kit={editor.kit} data={data} canWrite={canWrite} onBack={() => setView("kits")} onSaved={async (saved) => { await loadAll(); setEditor({ mode: "edit", kit: saved }); setNotice("Kit kaydedildi"); }}/>}
    {view === "catalogs" && <CatalogStatus
      data={data}
      canWrite={canWrite}
      onSynced={async () => { await loadAll(); setNotice("Katalog durumu güncellendi"); }}
    />}
  </div>;
}

function KitList({ kits, canWrite, onOpen, onChanged, setNotice }: { kits: Kit[]; canWrite: boolean; onOpen: (mode: EditorMode, kit?: Kit) => void; onChanged: () => Promise<void>; setNotice: (value: string) => void }) {
  const [query, setQuery] = useState(""); const visible = kits.filter((kit) => `${kit.name} ${kit.sku || ""}`.toLocaleLowerCase("tr").includes(query.toLocaleLowerCase("tr")));
  async function copy(kit: Kit) { const response = await apiFetch(`/api/kits/${kit.id}/copy`, json("POST", {})); if (!response.ok) return setNotice("Kit kopyalanamadı"); await onChanged(); setNotice(`${kit.name} kopyalandı`); }
  async function remove(kit: Kit) { if (!confirm(`“${kit.name}” kitini silmek istediğinize emin misiniz?`)) return; const response = await apiFetch(`/api/kits/${kit.id}`, { method: "DELETE" }); if (!response.ok) return setNotice("Kit silinemedi"); await onChanged(); setNotice("Kit silindi"); }
  return <main className="page-view"><div className="page-title"><div><span className="eyebrow">Kit oluşturma merkezi</span><h1>Kitler</h1><p>{kits.length} kayıt · maliyet ve kârlılık tek görünümde</p></div>{canWrite && <button className="primary-action" onClick={() => onOpen("create")}><Plus size={17}/>Yeni Kit</button>}</div><label className="page-search"><Search size={17}/><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Kit adı veya SKU ara"/></label>
    {visible.length === 0 ? <div className="empty-state"><Boxes size={34}/><h2>{kits.length ? "Aramanızla eşleşen kit yok" : "Henüz kit oluşturulmadı"}</h2><p>Bağlantı, profil kesimi ve tamamlayıcı ürünleri tek BOM içinde yönetin.</p>{canWrite && <button className="primary-action" onClick={() => onOpen("create")}><Plus size={17}/>İlk kiti oluştur</button>}</div> : <div className="kit-table-wrap"><table className="kit-table"><thead><tr><th>Kit</th><th>Toplam maliyet</th><th>Satış</th><th>Kâr</th><th>Marj</th><th>Güncelleme</th><th/></tr></thead><tbody>{visible.map((kit) => <tr key={kit.id}><td><div className="kit-identity">{kit.thumbnail ? <img src={kit.thumbnail} alt="" onError={imageFallback}/> : <span className="image-placeholder"><ImageOff size={18}/></span>}<div><strong>{kit.name}</strong><small>{kit.sku || "SKU yok"}</small></div></div></td><td>{money(kit.summary.total_cost_cents)}</td><td>{money(kit.sale_price_cents)}</td><td className={kit.summary.profit_cents >= 0 ? "positive" : "negative"}>{money(kit.summary.profit_cents)}</td><td>%{kit.summary.margin_percent.toFixed(1)}</td><td>{new Date(kit.updated_at).toLocaleString("tr-TR")}</td><td><div className="row-actions"><button title="Görüntüle" onClick={() => onOpen("view", kit)}><Search size={15}/></button>{canWrite && <><button title="Düzenle" onClick={() => onOpen("edit", kit)}><Edit3 size={15}/></button><button title="Kopyala" onClick={() => void copy(kit)}><Copy size={15}/></button><button className="danger" title="Sil" onClick={() => void remove(kit)}><Trash2 size={15}/></button></>}</div></td></tr>)}</tbody></table></div>}
  </main>;
}

function KitEditor({ mode, kit, data, canWrite, onBack, onSaved }: { mode: EditorMode; kit?: Kit; data: Bootstrap; canWrite: boolean; onBack: () => void; onSaved: (kit: Kit) => Promise<void> }) {
  const source = kit?.variants?.[0]; const readOnly = mode === "view" || !canWrite;
  const [name, setName] = useState(kit?.name || ""); const [sku, setSku] = useState(kit?.sku || ""); const [description, setDescription] = useState(kit?.description || ""); const [salePrice, setSalePrice] = useState(String((kit?.sale_price_cents || 0) / 100)); const [labor, setLabor] = useState(String((kit?.labor_cost_cents || 0) / 100)); const [packaging, setPackaging] = useState(String((kit?.packaging_cost_cents || 0) / 100)); const [other, setOther] = useState(String((kit?.other_cost_cents || 0) / 100));
  const [profileId, setProfileId] = useState(source?.profile_id || ""); const [connectors, setConnectors] = useState<Record<string, { productId: string; quantity: number }>>(() => Object.fromEntries((source?.connectors || []).map((line: any) => [line.connector_role, { productId: line.product_id, quantity: line.quantity }]))); const [cuts, setCuts] = useState<Array<{ id: string; quantity: number; length_mm: number }>>(() => (source?.cuts || []).map((cut: any) => ({ id: cut.id, quantity: cut.quantity, length_mm: cut.length_mm }))); const [complements, setComplements] = useState<Record<string, number>>(() => Object.fromEntries((source?.complementary_items || []).map((line: any) => [line.complementary_product_id, line.quantity_milli / 1000]))); const [picker, setPicker] = useState<"connector" | "profile" | "complement" | null>(null); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  const profile = data.profiles.find((item) => item.id === profileId); const connectorLines = Object.entries(connectors).map(([role, line]) => ({ role, quantity: line.quantity, item: data.connectors.find((item) => item.product_id === line.productId)! })).filter((line) => line.item); const complementLines = Object.entries(complements).map(([id, quantity]) => ({ quantity, item: data.complementaryProducts.find((item) => item.id === id)! })).filter((line) => line.item); const meters = cuts.reduce((sum, cut) => sum + cut.quantity * cut.length_mm, 0) / 1000;
  const connectorCost = connectorLines.reduce((sum, line) => sum + line.item.purchase_cost_cents * line.quantity, 0); const profileCost = Math.round((profile?.purchase_price_per_meter_cents || 0) * meters); const complementCost = complementLines.reduce((sum, line) => sum + line.item.purchase_unit_price_cents * line.quantity, 0); const extras = cents(labor) + cents(packaging) + cents(other); const total = connectorCost + profileCost + complementCost + extras; const sale = cents(salePrice); const profit = sale - total; const margin = sale > 0 ? profit / sale * 100 : 0; const warnings = connectorLines.filter((line) => !line.item.compatibility_group || (profile && line.item.compatibility_group !== profile.compatibility_group)).map((line) => `${line.item.sku}: ${line.item.compatibility_group || "uyumluluk bilgisi yok"}${profile ? ` ↔ ${profile.compatibility_group}` : ""}`); const maxKits = connectorLines.length ? Math.min(...connectorLines.map((line) => Math.floor(line.item.central_stock / line.quantity))) : 0;
  function addConnector(item: Connector) { const role = item.connector_role || item.form_code || item.form; if (!role) return; setConnectors((current) => ({ ...current, [role]: { productId: item.product_id, quantity: current[role]?.quantity || 1 } })); setPicker(null); }
  function addComplement(item: Complementary) { setComplements((current) => ({ ...current, [item.id]: current[item.id] || 1 })); setPicker(null); }
  async function save() { if (!name.trim() || !profile) return setError("Kit adı ve profil seçimi gerekli"); setSaving(true); setError(""); try { const metadata = { name: name.trim(), sku: sku.trim() || null, description, sale_price_cents: sale, labor_cost_cents: cents(labor), packaging_cost_cents: cents(packaging), other_cost_cents: cents(other) }; let working: Kit; if (mode === "create") { const response = await apiFetch("/api/kits", json("POST", { ...metadata, profile_id: profile.id })); if (!response.ok) throw new Error(await responseMessage(response)); working = await response.json(); } else { const response = await apiFetch(`/api/kits/${kit!.id}`, json("PUT", metadata)); if (!response.ok) throw new Error(await responseMessage(response)); working = await response.json(); } const variantId = working.variants[0].id; const response = await apiFetch(`/api/variants/${variantId}`, json("PUT", { profile_id: profile.id, connectors: connectorLines.map((line) => ({ role: line.role, product_id: line.item.product_id, quantity: line.quantity })), cuts: cuts.map(({ quantity, length_mm }) => ({ quantity, length_mm })), complementary_items: complementLines.map((line) => ({ product_id: line.item.id, quantity: line.quantity })) })); if (!response.ok) throw new Error(await responseMessage(response)); const fresh = await apiFetch(`/api/kits/${working.id}`); await onSaved(await fresh.json()); } catch (cause) { setError(cause instanceof Error ? cause.message : "Kit kaydedilemedi"); } finally { setSaving(false); } }
  return <main className="editor-page"><div className="editor-toolbar"><button className="back-button" onClick={onBack}><ChevronLeft size={18}/>Kitler</button><div><span className="eyebrow">{mode === "create" ? "Yeni kit" : mode === "view" ? "Kit detayı" : "Kit düzenleme"}</span><h1>{name || "Adsız kit"}</h1></div>{!readOnly && <button className="primary-action" disabled={saving} onClick={() => void save()}><Check size={17}/>{saving ? "Kaydediliyor…" : "Kaydet"}</button>}</div><div className="editor-grid"><section className="editor-main">
    <div className="card basic-card"><div className="card-title"><div><span className="eyebrow">Temel bilgiler</span><h2>Kit tanımı</h2></div></div><div className="form-grid"><label>Kit adı<input disabled={readOnly} value={name} onChange={(e) => setName(e.target.value)}/></label><label>SKU<input disabled={readOnly} value={sku} onChange={(e) => setSku(e.target.value)} placeholder="Örn. KIT-RAF-001"/></label><label className="span-2">Açıklama<textarea disabled={readOnly} value={description} onChange={(e) => setDescription(e.target.value)} rows={2}/></label><label>Satış fiyatı (₺)<input disabled={readOnly} type="number" min="0" step="0.01" value={salePrice} onChange={(e) => setSalePrice(e.target.value)}/></label></div></div>
    <BomSection title="Bağlantı Elemanları" count={`${connectorLines.reduce((sum, line) => sum + line.quantity, 0)} adet`} action={!readOnly && <button onClick={() => setPicker("connector")}><Plus size={15}/>Bağlantı Ekle</button>} empty={!connectorLines.length}>{connectorLines.map((line) => <ProductRow key={line.role} image={line.item.image ? `/api/panel/products/${encodeURIComponent(line.item.product_id)}/image` : undefined} badge={line.role} title={line.item.sku} subtitle={`${line.item.name_tr} · Stok ${line.item.central_stock} · Birim ${money(line.item.purchase_cost_cents)}`} cost={line.item.purchase_cost_cents * line.quantity} quantity={line.quantity} readOnly={readOnly} onQuantity={(quantity) => setConnectors((current) => ({ ...current, [line.role]: { ...current[line.role], quantity } }))} onRemove={() => setConnectors((current) => { const next = { ...current }; delete next[line.role]; return next; })}/>)}</BomSection>
    <BomSection title="Profiller" count={`${meters.toFixed(2)} m`} action={!readOnly && <button onClick={() => setPicker("profile")}><Plus size={15}/>{profile ? "Profili Değiştir" : "Profil Ekle"}</button>} empty={!profile}>{profile && <ProductRow image={profile.image_path} badge={profile.shape} title={profile.name} subtitle={`${profile.compatibility_group} · ${money(profile.purchase_price_per_meter_cents)}/m`} cost={profileCost} readOnly quantity={1}/>} {profile && <div className="cuts"><div className="cut-head"><strong>Kesim listesi</strong>{!readOnly && <button onClick={() => setCuts((current) => [...current, { id: crypto.randomUUID(), quantity: 1, length_mm: 1000 }])}><Plus size={14}/>Kesim</button>}</div>{cuts.map((cut, index) => <div className="cut-row" key={cut.id}><span>{index + 1}</span><label>Adet<input disabled={readOnly} type="number" min="1" value={cut.quantity} onChange={(e) => setCuts((current) => current.map((item) => item.id === cut.id ? { ...item, quantity: Math.max(1, Number(e.target.value)) } : item))}/></label><label>Uzunluk<input disabled={readOnly} type="number" min="1" value={cut.length_mm} onChange={(e) => setCuts((current) => current.map((item) => item.id === cut.id ? { ...item, length_mm: Math.max(1, Number(e.target.value)) } : item))}/><small>mm</small></label><strong>{(cut.quantity * cut.length_mm / 1000).toFixed(2)} m</strong>{!readOnly && <button className="remove" onClick={() => setCuts((current) => current.filter((item) => item.id !== cut.id))}><X size={15}/></button>}</div>)}</div>}</BomSection>
    <BomSection title="Tamamlayıcı Ürünler" count={`${complementLines.length} kalem`} action={!readOnly && <button onClick={() => setPicker("complement")}><Plus size={15}/>Ürün Ekle</button>} empty={!complementLines.length}>{complementLines.map((line) => <ProductRow key={line.item.id} image={complementImage(line.item)} badge={line.item.unit_type} title={line.item.name} subtitle={`${line.item.sku_optional || line.item.description || "Tamamlayıcı ürün"} · ${line.item.unit_type} · Birim ${money(line.item.purchase_unit_price_cents)}`} cost={line.item.purchase_unit_price_cents * line.quantity} quantity={line.quantity} readOnly={readOnly} onQuantity={(quantity) => setComplements((current) => ({ ...current, [line.item.id]: quantity }))} onRemove={() => setComplements((current) => { const next = { ...current }; delete next[line.item.id]; return next; })}/>)}</BomSection>
  </section><aside className="summary-card"><span className="eyebrow">Canlı fiyat özeti</span><h2>Kit maliyeti</h2><PriceLine label="Bağlantılar" value={connectorCost}/><PriceLine label="Profil" value={profileCost}/><PriceLine label="Tamamlayıcılar" value={complementCost}/><div className="extras"><strong>Ek maliyetler</strong><label>Kesim / İşçilik<input disabled={readOnly} type="number" min="0" step=".01" value={labor} onChange={(e) => setLabor(e.target.value)}/></label><label>Paketleme<input disabled={readOnly} type="number" min="0" step=".01" value={packaging} onChange={(e) => setPackaging(e.target.value)}/></label><label>Diğer<input disabled={readOnly} type="number" min="0" step=".01" value={other} onChange={(e) => setOther(e.target.value)}/></label></div><div className="summary-total"><PriceLine label="Toplam maliyet" value={total}/><PriceLine label="Satış fiyatı" value={sale}/><PriceLine label="Net kâr" value={profit} tone={profit >= 0 ? "positive" : "negative"}/><div className="margin"><span>Marj</span><strong>%{margin.toFixed(1)}</strong></div></div>{connectorLines.length > 0 && <div className="stock-note"><Boxes size={16}/><span>Bağlantı stoklarına göre en fazla <strong>{maxKits}</strong> kit</span></div>}{warnings.length > 0 && <div className="warning-box"><AlertTriangle size={17}/><div><strong>Uyumluluk uyarısı</strong>{warnings.map((warning) => <span key={warning}>{warning}</span>)}</div></div>}{error && <div className="error-box">{error}</div>}{!readOnly && <button className="primary-action full" disabled={saving} onClick={() => void save()}><Check size={17}/>{saving ? "Kaydediliyor…" : "Kiti Kaydet"}</button>}</aside></div>{picker && <CatalogPicker kind={picker} data={data} onClose={() => setPicker(null)} onConnector={addConnector} onProfile={(item) => { setProfileId(item.id); setPicker(null); }} onComplement={addComplement}/>}</main>;
}

function BomSection({ title, count, action, empty, children }: { title: string; count: string; action?: ReactNode; empty: boolean; children: ReactNode }) { return <section className="card bom-card"><div className="card-title"><div><h2>{title}</h2><span>{count}</span></div>{action}</div>{empty ? <div className="empty-row">Henüz seçim yapılmadı</div> : children}</section>; }
function ProductRow({ image, badge, title, subtitle, cost, quantity = 1, readOnly, onQuantity, onRemove }: { image?: string; badge: string; title: string; subtitle: string; cost: number; quantity?: number; readOnly: boolean; onQuantity?: (value: number) => void; onRemove?: () => void }) { return <div className="product-row">{image ? <img src={image} alt="" onError={imageFallback}/> : <span className="row-badge">{badge.slice(0, 4)}</span>}<div className="product-copy"><strong>{title}</strong><span>{subtitle}</span></div>{onQuantity && <div className="stepper"><button disabled={readOnly} onClick={() => quantity <= 1 ? onRemove?.() : onQuantity(quantity - 1)}>−</button><input disabled={readOnly} value={quantity} type="number" min=".001" step=".001" onChange={(e) => onQuantity(Math.max(.001, Number(e.target.value)))}/><button disabled={readOnly} onClick={() => onQuantity(quantity + 1)}>+</button></div>}<strong className="row-cost">{money(cost)}</strong>{onRemove && !readOnly && <button className="remove" onClick={onRemove}><Trash2 size={15}/></button>}</div>; }
function PriceLine({ label, value, tone = "" }: { label: string; value: number; tone?: string }) { return <div className={`price-line ${tone}`}><span>{label}</span><strong>{money(value)}</strong></div>; }

function CatalogPicker({ kind, data, onClose, onConnector, onProfile, onComplement }: { kind: "connector" | "profile" | "complement"; data: Bootstrap; onClose: () => void; onConnector: (item: Connector) => void; onProfile: (item: Profile) => void; onComplement: (item: Complementary) => void }) {
  const [query, setQuery] = useState(""); const [page, setPage] = useState(0); const pageSize = 30; const source: Array<Connector | Profile | Complementary> = kind === "connector" ? data.connectors : kind === "profile" ? data.profiles : data.complementaryProducts; const filtered = source.filter((item: any) => Object.values(item).filter((value) => typeof value === "string" || typeof value === "number").join(" ").toLocaleLowerCase("tr").includes(query.toLocaleLowerCase("tr"))); const pages = Math.max(1, Math.ceil(filtered.length / pageSize)); const visible = filtered.slice(page * pageSize, (page + 1) * pageSize);
  return <div className="modal-backdrop"><div className="catalog-modal"><div className="modal-head"><div><span className="eyebrow">Merkezi Panel kataloğu</span><h2>{kind === "connector" ? "Bağlantı elemanı seç" : kind === "profile" ? "Profil seç" : "Tamamlayıcı ürün seç"}</h2></div><button onClick={onClose}><X size={19}/></button></div><label className="modal-search"><Search size={17}/><input autoFocus value={query} onChange={(e) => { setQuery(e.target.value); setPage(0); }} placeholder="SKU, ad, malzeme, form, ölçü veya model ara"/></label><div className="catalog-results">{visible.map((raw: any) => { const connector = kind === "connector" ? raw as Connector : null; const profile = kind === "profile" ? raw as Profile : null; const complement = kind === "complement" ? raw as Complementary : null; const id = connector?.product_id || profile?.id || complement!.id; const title = connector?.sku || profile?.name || complement!.name; const subtitle = connector ? `${connector.name_tr} · ${connector.material || ""} ${connector.size || connector.normalized_pipe_size || ""}` : profile ? `${profile.material} · ${profile.compatibility_group}${profile.wall_thickness_mm ? ` · ${profile.wall_thickness_mm} mm et` : ""}${profile.supplier_name ? ` · ${profile.supplier_name}` : ""}` : `${complement!.sku_optional || complement!.unit_type} · ${money(complement!.purchase_unit_price_cents)}`; const image = connector?.image ? `/api/panel/products/${encodeURIComponent(id)}/image` : profile?.image_path || (complement ? complementImage(complement) : undefined); return <button className="catalog-result" key={id} onClick={() => connector ? onConnector(connector) : profile ? onProfile(profile) : onComplement(complement!)}>{image ? <img src={image} alt="" onError={imageFallback}/> : <span className="image-placeholder"><ImageOff size={17}/></span>}<div><strong>{title}</strong><span>{subtitle}</span></div><PackagePlus size={18}/></button>; })}{visible.length === 0 && <div className="empty-row">Sonuç bulunamadı</div>}</div><div className="pagination"><span>{filtered.length} ürün · Sayfa {page + 1}/{pages}</span><div><button disabled={page === 0} onClick={() => setPage((value) => value - 1)}><ChevronLeft size={16}/></button><button disabled={page >= pages - 1} onClick={() => setPage((value) => value + 1)}><ChevronRight size={16}/></button></div></div></div></div>;
}

function CatalogStatus({ data, canWrite, onSynced }: { data: Bootstrap; canWrite: boolean; onSynced: () => Promise<void> }) { const [busy, setBusy] = useState(false); const [mapping, setMapping] = useState<Connector | null>(null); async function sync() { setBusy(true); const response = await apiFetch("/api/panel/sync", { method: "POST" }); if (response.ok) await onSynced(); setBusy(false); } return <main className="page-view"><div className="page-title"><div><span className="eyebrow">Merkezi katalog</span><h1>Panel senkronizasyonu</h1><p>Kit Studio katalogları Panel verisinin salt-okunur önbelleğidir.</p></div>{canWrite && <button className="primary-action" disabled={busy} onClick={() => void sync()}><RefreshCw size={17}/>{busy ? "Senkronize ediliyor…" : "Şimdi senkronize et"}</button>}</div><div className={`sync-banner ${data.sync.panelReachable ? "reachable" : "stale"}`}><strong>{data.sync.panelReachable ? "Panel erişilebilir" : "Panel erişilemiyor — son önbellek korunuyor"}</strong><span>Son başarılı: {data.sync.lastSyncedAt ? new Date(data.sync.lastSyncedAt).toLocaleString("tr-TR") : "yok"}</span>{data.sync.lastError && <small>{data.sync.lastError}</small>}</div><div className="stat-grid"><Stat label="Bağlantı" value={data.sync.connectorCount}/><Stat label="Profil" value={data.sync.profileCount}/><Stat label="Tamamlayıcı" value={data.sync.complementCount}/><Stat label="Uyumluluk bekleyen" value={data.sync.unresolvedCount}/></div>{data.sync.unresolvedCount > 0 && <div className="card unresolved-card"><h2>Uyumluluk bekleyen bağlantılar</h2>{data.connectors.filter((item) => item.compatibility_status === "UNRESOLVED").map((item) => <div key={item.product_id}><span><strong>{item.sku}</strong><small>{item.name_tr} · {item.compatibility_note}</small></span>{data.user.role === "admin" && <button onClick={() => setMapping(item)}>Manuel eşle</button>}</div>)}</div>}{mapping && <ManualMapping connector={mapping} onClose={() => setMapping(null)} onSaved={async () => { setMapping(null); await onSynced(); }}/>}</main>; }

function ManualMapping({ connector, onClose, onSaved }: { connector: Connector; onClose: () => void; onSaved: () => Promise<void> }) {
  const [role, setRole] = useState(connector.form_code || "ELB"); const [shape, setShape] = useState<"SQUARE" | "RECTANGULAR" | "ROUND">("SQUARE"); const [width, setWidth] = useState(""); const [height, setHeight] = useState(""); const [diameter, setDiameter] = useState(""); const [group, setGroup] = useState(""); const [material, setMaterial] = useState(connector.material || ""); const [error, setError] = useState("");
  async function submit(event: FormEvent) { event.preventDefault(); const response = await apiFetch("/api/connector-compatibility", json("POST", { product_id: connector.product_id, connector_role: role, profile_shape: shape, profile_width_mm: shape === "ROUND" ? undefined : Number(width), profile_height_mm: shape === "ROUND" ? undefined : Number(height), outside_diameter_mm: shape === "ROUND" ? Number(diameter) : undefined, compatible_material_group: material || undefined, compatibility_group: group })); if (!response.ok) return setError("Eşleme kaydedilemedi"); await onSaved(); }
  return <div className="modal-backdrop"><form className="mapping-modal" onSubmit={submit}><div className="modal-head"><div><span className="eyebrow">Yönetici eşlemesi</span><h2>{connector.sku}</h2></div><button type="button" onClick={onClose}><X size={19}/></button></div><div className="mapping-fields"><label>Bağlantı rolü<input required value={role} onChange={(e) => setRole(e.target.value.toUpperCase())}/></label><label>Profil şekli<select value={shape} onChange={(e) => setShape(e.target.value as typeof shape)}><option value="SQUARE">Kare</option><option value="RECTANGULAR">Dikdörtgen</option><option value="ROUND">Yuvarlak</option></select></label>{shape === "ROUND" ? <label>Dış çap (mm)<input required type="number" min="0.1" step="any" value={diameter} onChange={(e) => setDiameter(e.target.value)}/></label> : <><label>Genişlik (mm)<input required type="number" min="0.1" step="any" value={width} onChange={(e) => setWidth(e.target.value)}/></label><label>Yükseklik (mm)<input required type="number" min="0.1" step="any" value={height} onChange={(e) => setHeight(e.target.value)}/></label></>}<label>Uyumluluk grubu<input required placeholder="SQ-20X20 veya RD-33.7" value={group} onChange={(e) => setGroup(e.target.value)}/></label><label>Malzeme grubu<input value={material} onChange={(e) => setMaterial(e.target.value)}/></label>{error && <div className="error-box">{error}</div>}<div className="modal-actions"><button type="button" onClick={onClose}>Vazgeç</button><button className="primary-action" type="submit">Eşlemeyi kaydet</button></div></div></form></div>;
}
function Stat({ label, value }: { label: string; value: number }) { return <article className="stat"><Boxes/><span>{label}</span><strong>{value}</strong></article>; }
function LoginScreen({ onSubmit, error }: { onSubmit: (event: FormEvent<HTMLFormElement>) => void; error: string }) { return <div className="auth-screen"><form onSubmit={onSubmit}><div className="brand-mark"><Wrench size={18}/></div><span className="eyebrow">DSDST Kit Studio</span><h1>Panel hesabınızla giriş yapın</h1><p>Kullanıcı adı ve parola doğrudan Panel sunucusunda doğrulanır.</p><input name="username" autoComplete="username" autoFocus placeholder="Kullanıcı adı"/><input name="password" type="password" autoComplete="current-password" placeholder="Parola"/><button className="primary-action full" type="submit">Giriş yap</button>{error && <small>{error}</small>}</form></div>; }
function PasswordChange({ user, onChanged, onLogout }: { user: User; onChanged: (user: User) => void; onLogout: () => void }) { const [error, setError] = useState(""); async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); if (form.get("new") !== form.get("confirm")) return setError("Yeni parolalar eşleşmiyor"); const response = await apiFetch("/api/auth/change-password", json("POST", { current_password: form.get("current"), new_password: form.get("new") })); if (!response.ok) return setError("Parola değiştirilemedi"); onChanged((await response.json()).user); } return <div className="auth-screen"><form onSubmit={submit}><span className="eyebrow">{user.username}</span><h1>Parolanızı değiştirin</h1><input name="current" type="password" placeholder="Mevcut parola"/><input name="new" type="password" minLength={8} placeholder="Yeni parola"/><input name="confirm" type="password" minLength={8} placeholder="Yeni parola tekrar"/><button className="primary-action full">Parolayı değiştir</button><button type="button" className="link-button" onClick={onLogout}>Çıkış yap</button>{error && <small>{error}</small>}</form></div>; }
function cents(value: string) { return Math.max(0, Math.round((Number(value) || 0) * 100)); }
function complementImage(item: Complementary) { return item.image_path ? (item.catalog_source === "PANEL" ? `/api/panel/complementary-products/${encodeURIComponent(item.id)}/image` : item.image_path) : undefined; }
function imageFallback(event: SyntheticEvent<HTMLImageElement>) { event.currentTarget.onerror = null; event.currentTarget.src = "/favicon.svg"; }
async function responseMessage(response: Response) { const body = await response.json().catch(() => ({})); return body.error === "DUPLICATE_SKU" ? "Bu SKU başka bir kitte kullanılıyor" : body.error || "İşlem tamamlanamadı"; }
